---
- name: Building and running Jupyter Notebook container
  hosts: localhost
  vars_prompt:
  - name: jupyternotebook_version
    prompt: "Enter the Jupyter notebook version you require - ensure it is available as a tag at https://hub.docker.com/r/jupyter/datascience-notebook/tags/ e.g. notebook-6.4.5"
    private: no
  - name: pubkey_path
    prompt: "Enter the path to your ssh public key on your local machine, e.g. ~/.ssh/id_rsa.key.pub"
    private: no
  tasks:
  - name: Pulling the Singularity container
    command: singularity pull docker://jupyter/datascience-notebook:{{ jupyternotebook_version }}
    become: yes
    args:
      creates: "datascience-notebook_{{ jupyternotebook_version }}.sif"
  - name: Create a data folder
    command: mkdir /data
    become: yes
    args:
      creates: /data
  - name: Change ownership of data folder
    command: chown ubuntu:ubuntu /data
    become: yes
    args:
      warn: false
  - name: Mount data folder
    command: mount /dev/vdc /data
    become: yes
    ignore_errors: yes
  - name: Run Jupyter Notebook server
    shell: nohup singularity exec -B $PWD datascience-notebook_{{ jupyternotebook_version }}.sif jupyter notebook --ip='0.0.0.0' --port=8888 --no-browser --allow-root &
    become: yes
  - name: Run instructions script
    script: run_jupyternotebook.sh '{{ pubkey_path }}' '{{ jupyternotebook_version }}'
    become: yes
    register: result
  - name: Print Jupyter Notebook instructions
    debug: 
      var: result.stdout_lines
